### ISSUE TITLE
Config: Some input after EndOfFile.

### ISSUE THREAD

**Issue by sistematico** [ebaydayz/ESSV2#3]
I'm receiving this error: Config: Some input after EndOfFile. on OverWatch 0.2.5 Windows DS.

```
Client RPT:
_maxlocalspawned = _maxlo>
  Error position: <_offset)
]);


_maxlocalspawned = _maxlo>
  Error Undefined variable in expression: _offset
File z\addons\dayz_code\compile\player_spawnCheck.sqf, line 59
"SpawnCheck Local.Agents: 0/30, NearBy.Agents: 0/60, Global.Agents: 0/3000, W.holders: 0/80, (radius:200m 50fps,scalar Timer)."
Error in expression <ders,_maxWeaponHolders,(diag_tickTime + _offset)
]);
```

Thank you.

**Comment by ebaydayz** [comment]
Hi,

The client RPT error you posted is unrelated. It is an error in the Overwatch dayz_code player_spawnCheck.sqf file. 

Some input after EndOfFile means there is a problem in a config file. Usually something is in the wrong place, outside of the last class closing brace };. If it is a new error that you were not getting before double check your description.ext.

**Comment by sistematico** [comment]
Hello ebay! Thanks for your reply!

description.ext: https://gist.github.com/sistematico/02f3fa506c9f0dcfa624
start.bat: `start .\Expansion\beta\arma2oaserver.exe -mod=@DayzOverwatch;@DayzOverwatch_Server -name=dayz_overwatch -config=dayz_overwatch\config_guerrilha.cfg -cfg=dayz_overwatch\basic.cfg -profiles=dayz_overwatch`
Error log: https://gist.github.com/sistematico/57a5ed155c15083305d5
Error image: http://i.imgur.com/gri5djb.png

I'm using this files: https://github.com/scrumbee/DayzOverwatch-Server

Any help is welcome.

**Comment by sistematico** [comment]
BTW, i don't have the player_spawnCheck.sqf file: http://i.imgur.com/GyGwTGG.png

**Comment by ebaydayz** [comment]
You have an extra }; on line 177 of description.ext that is not used for anything. Remove that and you should be good. 

I suggest using an editor with syntax highlighting like NotePad++ so you can highlight each curly brace and make sure it has a corresponding opening/closing curly brace in the future.

**Comment by sistematico** [comment]
Awesome!!!
All working now!
Sorry for my nobbiness! hahaha

Thank you ebay!
