### ISSUE TITLE
Gear closes parachute

### ISSUE THREAD

**Issue by sistematico** [ebaydayz/ESSV2#5]
When i open my gear, parachutes closes.

Client LOG: https://gist.github.com/sistematico/3a79abcd148f124e8150
Server LOG: https://gist.github.com/sistematico/fc93f3f2b502dfc38bf2

Any help is welcome.

**Comment by sistematico** [comment]
I don't know why, but now is fixed!

Sorry.

**Comment by sistematico** [comment]
No, the error still present with esc menu...

**Comment by ebaydayz** [comment]
Sorry for the late reply, but I can not reproduce this in testing. 

If you are running vanilla dayz or overwatch make sure you did the optional things under step#11:
http://opendayz.net/threads/release-essv2-enhanced-spawn-selection-v2.21547/

Specifically if you do not make the changes under "If using halo:" then the parachute will be deleted.
