### ISSUE TITLE
Class Selection Menu

### ISSUE THREAD

**Issue by sistematico** [ebaydayz/ESSV2#6]
How to remove class selections but keep loadout?
Like WICKED?

Thank you!

**Comment by ebaydayz** [comment]
Follow the steps in the FAQ for removing class selection:
http://opendayz.net/threads/release-essv2-enhanced-spawn-selection-v2.21547/

Then you can use any other script or method to customize the starting loadout. The easiest is the official epoch init.sqf variables:
http://epochmod.gamepedia.com/A2Epoch:Init.sqf#Customize_fresh_spawn_loadout
