### ISSUE TITLE
Spawn with nothing/Spawn in debug

### ISSUE THREAD

**Issue by coldmike01** [ebaydayz/ESSV2#7]
Hello, i have been having issues, Im hopeful maybe we can figure out what the issue is.  Have had this issue since install origonally. Unsure if you need any other files/information, Any help is greatly appreciated.

<pre><code>
_publicClasses = [

        ["Survivor","Soldier_TL_PMC_DZ","BanditW1_DZ",["10x_303",3],["LeeEnfield"],"",[],[],0,0,0],
        ["Bandit 1","GUE_soldier_Crew_DZ","BanditW2_DZ",["30Rnd_545x39_AK",3],["AK_74"],"",[],[],0,-5000,0],
        ["Bandit 2","GUE_soldier_Crew_DZ","BanditW2_DZ",["30Rnd_545x39_AK",3],["AK_107_PSO"],"",[],[],0,-15000,0],
        ["Bandit 3","GUE_soldier_Crew_DZ","BanditW2_DZ",["5Rnd_127x99_as50",3],["BAF_AS50_scoped_DZ","NVGoggles"],"",[],[],0,-50000,0],
        ["Hero 1","GUE_Soldier_Sniper_DZ","BanditW2_DZ",["30Rnd_556x45_Stanag",3],["M4A1"],"",[],[],0,5000,0],
        ["Hero 2","GUE_Soldier_Sniper_DZ","BanditW2_DZ",["30Rnd_556x45_Stanag",3],["RH_hk416sacog"],"",[],[],0,10000,0],
        ["Hero 3","GUE_Soldier_Sniper_DZ","BanditW2_DZ",["5Rnd_127x99_as50",3],["BAF_AS50_scoped_DZ","NVGoggles"],"",[],[],0,15000,0],
	
	["VIP Scout","INS_Soldier_AR_DZ","SurvivorW3_DZ",["100Rnd_556x45_BetaCMag",3,"15Rnd_9x19_M9SD",3,"ItemAntibiotic","ItemBloodbag","ItemEpinephrine","ItemMorphine"],["m16a4_acg","M9SD","Binocular_Vector","NVGoggles","ItemCompass","ItemKnife","ItemGPS"],"DZ_Backpack_EP1",[],[],1,0,0],
	["VIP Specialist","INS_Soldier_CO_DZ","SurvivorWdesert_DZ",["100Rnd_762x51_M240",3,"30Rnd_9x19_UZI_SD",3,"ItemAntibiotic","ItemBloodbag","ItemEpinephrine","ItemMorphine"],["Mk_48_DZ","UZI_SD_EP1","Binocular_Vector","NVGoggles","ItemCompass","ItemKnife","ItemGPS"],"DZ_Backpack_EP1",[],[],2,0,0],
	["VIP Sniper","GUE_Soldier_Sniper_DZ","SurvivorWurban_DZ",["20Rnd_762x51_DMR",3,"30Rnd_9x19_UZI_SD",3,"ItemAntibiotic","ItemBloodbag","ItemEpinephrine","ItemMorphine"],["DMR","UZI_SD_EP1","Binocular_Vector","NVGoggles","ItemCompass","ItemKnife","ItemGPS"],"DZ_Backpack_EP1",[],[],3,0,0]
];

case "chernarus":{
		[
			["Random",[[4523,2444,0],[12037,9100,0],[6723,2562,0],[10417,2120,0],[1896,2242,0],[13470,6306,0]],0,0,1], // Random will never be blocked, so always keep it if using body check.
			["Balota",[4523,2444,0],0,0],
			["Berezino",[12037,9100,0],0,0],
			["Cherno",[6723,2562,0],0,0],
			["Elektro",[10417,2120,0],0,0],
			["Kamenka",[1896,2242,0],0,0],
			["Solnichny",[13470,6306,0],0,0],
			// Above are defaults
			["Devils AI COMPOUND",[6900,11419,0],0,0],
["Gorka",[9659,8839,0],0,0],
			["Grishino",[5967,10323,0],0,0],
			["Guglovo",[8472,6754,0],0,0],
			["Gvozdno",[8654,11832,0],0,0],
			["Kabanino",[5346,8630,0],0,0],
			["Kamyshovo",[12073,3490,0],0,0],
			["Komarovo",[3643,2473,0],0,0],
			["Krasnostav",[11342,12232,0],0,0],
			["Krutoy",[13395,4159,0],0,0],
			["Lopatino",[2731,10000,0],0,0],
			["Petrovka",[5035,12459,0],0,0],
			["Pogorevka",[4461,6424,0],0,0],
			["Prigor",[8059,3381,0],0,0],
			["Pusta",[9178,3928,0],0,0],
			["Vybor",[3893,8883,0],0,0],
			["Vyshnoye",[6612,6065,0],0,0],
			["Zelenogorsk",[2858,5313,0],0,0],
			["Bandit Base",[1607,7804,0],0,-7500],
			["Hero Hideout",[12944,12767,0],0,7500]
		]
</code></pre>

**Comment by ebaydayz** [comment]
Sorry for the late reply. If you are still having this problem pastebin your client and server RPT:
http://opendayz.net/threads/support-essv2-enhanced-spawn-selection-v2.21552/

**Comment by ebaydayz** [comment]
Should be fixed with:
https://github.com/ebaydayz/ESSV2/commit/5b603adde77dfcfd8ff945ee6f427a5333acb2c7
